apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: mission-clock-package
  namespace: mission-clock

spec:
  network:
    expose:
      - service: frontend-service
        selector:
          app: frontend
        host: missionclock
        port: 8080

    allow:
      - description: "Allow egress communication within the namespace."
        direction: Egress
        remoteGenerated: IntraNamespace

      - description: "Allow ingress communication within the namespace."
        direction: Ingress
        remoteGenerated: IntraNamespace

  sso:
    - name: Mission Clock SSO
      clientId: missionclock
      redirectUris:
        - "https://missionclock.dev.ai.army.mil/success"
      enableAuthserviceSelector:
        app: frontend